[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.3.0"
async-channel = "2.0.0"
async-dup = "1.2.2"
crossterm = "0.27.0"
ratatui = "0.24.0"
#viuer = "0.7.1"

[[bin]]
name = "client"
path = "src/client/client.rs"

[[bin]]
name = "server"
path = "src/server/server.rs"

[[bin]]
name = "gui-test"
path = "src/gui-test.rs"